[package]
name = "direnv_rust"
version = "0.1.0"
authors = ["Shunsuke Kirino <shunsuke.kirino@gmail.com>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
ansi_term = "0.9"
sha1 = "0.2"
